version: "3.8"

services:
  web:
    build: .
    container_name: songshelf-web
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_NAME=songshelf
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: songshelf-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: songshelf
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
